// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type InfiniteData, infiniteQueryOptions, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { AuthService, ChatService, type Options, ServerService, UserService } from '../sdk.gen';
import type { AuthLoginData, AuthLoginError, AuthLoginResponse, AuthLogoutData, AuthLogoutError, AuthLogoutResponse, AuthRefreshData, AuthRefreshError, AuthRefreshResponse, AuthRegisterData, AuthRegisterError, AuthRegisterResponse, ChatsCreateChatData, ChatsCreateChatError, ChatsCreateChatResponse, ChatsGetMyChatsData, ChatsGetMyChatsError, ChatsGetMyChatsResponse, ServersCreateServerData, ServersCreateServerError, ServersCreateServerResponse, ServersDeleteServerData, ServersDeleteServerError, ServersDeleteServerResponse, ServersGetMyServerData, ServersGetMyServerError, ServersGetMyServerResponse, ServersGetMyServersData, ServersGetMyServersResponse, ServersUpdateServerData, ServersUpdateServerError, ServersUpdateServerResponse, UsersDeleteUserData, UsersDeleteUserResponse, UsersGetCurrentUserData, UsersGetCurrentUserResponse, UsersGetUserByIdData, UsersGetUserByIdError, UsersGetUserByIdResponse, UsersUpdateUserData, UsersUpdateUserError, UsersUpdateUserResponse } from '../types.gen';

/**
 * Register
 */
export const authRegisterMutation = (options?: Partial<Options<AuthRegisterData>>): UseMutationOptions<AuthRegisterResponse, AuthRegisterError, Options<AuthRegisterData>> => {
    const mutationOptions: UseMutationOptions<AuthRegisterResponse, AuthRegisterError, Options<AuthRegisterData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await AuthService.register({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Login
 */
export const authLoginMutation = (options?: Partial<Options<AuthLoginData>>): UseMutationOptions<AuthLoginResponse, AuthLoginError, Options<AuthLoginData>> => {
    const mutationOptions: UseMutationOptions<AuthLoginResponse, AuthLoginError, Options<AuthLoginData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await AuthService.login({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Refresh token
 */
export const authRefreshMutation = (options?: Partial<Options<AuthRefreshData>>): UseMutationOptions<AuthRefreshResponse, AuthRefreshError, Options<AuthRefreshData>> => {
    const mutationOptions: UseMutationOptions<AuthRefreshResponse, AuthRefreshError, Options<AuthRefreshData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await AuthService.refresh({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Logout
 */
export const authLogoutMutation = (options?: Partial<Options<AuthLogoutData>>): UseMutationOptions<AuthLogoutResponse, AuthLogoutError, Options<AuthLogoutData>> => {
    const mutationOptions: UseMutationOptions<AuthLogoutResponse, AuthLogoutError, Options<AuthLogoutData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await AuthService.logout({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete User
 */
export const usersDeleteUserMutation = (options?: Partial<Options<UsersDeleteUserData>>): UseMutationOptions<UsersDeleteUserResponse, DefaultError, Options<UsersDeleteUserData>> => {
    const mutationOptions: UseMutationOptions<UsersDeleteUserResponse, DefaultError, Options<UsersDeleteUserData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await UserService.deleteUser({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const usersGetCurrentUserQueryKey = (options?: Options<UsersGetCurrentUserData>) => createQueryKey('usersGetCurrentUser', options);

/**
 * Get current user
 */
export const usersGetCurrentUserOptions = (options?: Options<UsersGetCurrentUserData>) => queryOptions<UsersGetCurrentUserResponse, DefaultError, UsersGetCurrentUserResponse, ReturnType<typeof usersGetCurrentUserQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await UserService.getCurrentUser({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: usersGetCurrentUserQueryKey(options)
});

/**
 * Update current user
 */
export const usersUpdateUserMutation = (options?: Partial<Options<UsersUpdateUserData>>): UseMutationOptions<UsersUpdateUserResponse, UsersUpdateUserError, Options<UsersUpdateUserData>> => {
    const mutationOptions: UseMutationOptions<UsersUpdateUserResponse, UsersUpdateUserError, Options<UsersUpdateUserData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await UserService.updateUser({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const usersGetUserByIdQueryKey = (options: Options<UsersGetUserByIdData>) => createQueryKey('usersGetUserById', options);

/**
 * Get user by id
 */
export const usersGetUserByIdOptions = (options: Options<UsersGetUserByIdData>) => queryOptions<UsersGetUserByIdResponse, UsersGetUserByIdError, UsersGetUserByIdResponse, ReturnType<typeof usersGetUserByIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await UserService.getUserById({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: usersGetUserByIdQueryKey(options)
});

export const chatsGetMyChatsQueryKey = (options?: Options<ChatsGetMyChatsData>) => createQueryKey('chatsGetMyChats', options);

/**
 * Get My Chats
 */
export const chatsGetMyChatsOptions = (options?: Options<ChatsGetMyChatsData>) => queryOptions<ChatsGetMyChatsResponse, ChatsGetMyChatsError, ChatsGetMyChatsResponse, ReturnType<typeof chatsGetMyChatsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ChatService.getMyChats({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: chatsGetMyChatsQueryKey(options)
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = { ...queryKey[0] };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const chatsGetMyChatsInfiniteQueryKey = (options?: Options<ChatsGetMyChatsData>): QueryKey<Options<ChatsGetMyChatsData>> => createQueryKey('chatsGetMyChats', options, true);

/**
 * Get My Chats
 */
export const chatsGetMyChatsInfiniteOptions = (options?: Options<ChatsGetMyChatsData>) => infiniteQueryOptions<ChatsGetMyChatsResponse, ChatsGetMyChatsError, InfiniteData<ChatsGetMyChatsResponse>, QueryKey<Options<ChatsGetMyChatsData>>, string | null | Pick<QueryKey<Options<ChatsGetMyChatsData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<ChatsGetMyChatsData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                cursor: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await ChatService.getMyChats({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: chatsGetMyChatsInfiniteQueryKey(options)
});

/**
 * Create Chat
 */
export const chatsCreateChatMutation = (options?: Partial<Options<ChatsCreateChatData>>): UseMutationOptions<ChatsCreateChatResponse, ChatsCreateChatError, Options<ChatsCreateChatData>> => {
    const mutationOptions: UseMutationOptions<ChatsCreateChatResponse, ChatsCreateChatError, Options<ChatsCreateChatData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await ChatService.createChat({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const serversGetMyServersQueryKey = (options?: Options<ServersGetMyServersData>) => createQueryKey('serversGetMyServers', options);

/**
 * Get My Servers
 */
export const serversGetMyServersOptions = (options?: Options<ServersGetMyServersData>) => queryOptions<ServersGetMyServersResponse, DefaultError, ServersGetMyServersResponse, ReturnType<typeof serversGetMyServersQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ServerService.getMyServers({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: serversGetMyServersQueryKey(options)
});

/**
 * Create Server
 */
export const serversCreateServerMutation = (options?: Partial<Options<ServersCreateServerData>>): UseMutationOptions<ServersCreateServerResponse, ServersCreateServerError, Options<ServersCreateServerData>> => {
    const mutationOptions: UseMutationOptions<ServersCreateServerResponse, ServersCreateServerError, Options<ServersCreateServerData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await ServerService.createServer({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete Server
 */
export const serversDeleteServerMutation = (options?: Partial<Options<ServersDeleteServerData>>): UseMutationOptions<ServersDeleteServerResponse, ServersDeleteServerError, Options<ServersDeleteServerData>> => {
    const mutationOptions: UseMutationOptions<ServersDeleteServerResponse, ServersDeleteServerError, Options<ServersDeleteServerData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await ServerService.deleteServer({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const serversGetMyServerQueryKey = (options: Options<ServersGetMyServerData>) => createQueryKey('serversGetMyServer', options);

/**
 * Get My Server
 */
export const serversGetMyServerOptions = (options: Options<ServersGetMyServerData>) => queryOptions<ServersGetMyServerResponse, ServersGetMyServerError, ServersGetMyServerResponse, ReturnType<typeof serversGetMyServerQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ServerService.getMyServer({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: serversGetMyServerQueryKey(options)
});

/**
 * Update Server
 */
export const serversUpdateServerMutation = (options?: Partial<Options<ServersUpdateServerData>>): UseMutationOptions<ServersUpdateServerResponse, ServersUpdateServerError, Options<ServersUpdateServerData>> => {
    const mutationOptions: UseMutationOptions<ServersUpdateServerResponse, ServersUpdateServerError, Options<ServersUpdateServerData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await ServerService.updateServer({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
