// This file is auto-generated by @hey-api/openapi-ts

import { queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { AuthService, ChatService, type Options, ServerService, UserService } from '../sdk.gen';
import type { AuthLoginUserData, AuthLoginUserError, AuthLoginUserResponse, AuthRefreshData, AuthRefreshError, AuthRefreshResponse, AuthRegisterUserData, AuthRegisterUserError, AuthRegisterUserResponse, ChatsCreateChatData, ChatsCreateChatError, ChatsCreateChatResponse, ServersCreateServerData, ServersCreateServerError, ServersCreateServerResponse, ServersDeleteServerData, ServersDeleteServerError, ServersDeleteServerResponse, ServersGetMyServersData, ServersGetMyServersError, ServersGetMyServersResponse, ServersUpdateServerData, ServersUpdateServerError, ServersUpdateServerResponse, UsersGetCurrentUserData, UsersGetCurrentUserError, UsersGetCurrentUserResponse } from '../types.gen';

/**
 * Register new user
 *
 * Register new user
 */
export const authRegisterUserMutation = (options?: Partial<Options<AuthRegisterUserData>>): UseMutationOptions<AuthRegisterUserResponse, AuthRegisterUserError, Options<AuthRegisterUserData>> => {
    const mutationOptions: UseMutationOptions<AuthRegisterUserResponse, AuthRegisterUserError, Options<AuthRegisterUserData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await AuthService.registerUser({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Login user
 *
 * Login user
 */
export const authLoginUserMutation = (options?: Partial<Options<AuthLoginUserData>>): UseMutationOptions<AuthLoginUserResponse, AuthLoginUserError, Options<AuthLoginUserData>> => {
    const mutationOptions: UseMutationOptions<AuthLoginUserResponse, AuthLoginUserError, Options<AuthLoginUserData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await AuthService.loginUser({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Refresh token
 *
 * Refresh token
 */
export const authRefreshMutation = (options?: Partial<Options<AuthRefreshData>>): UseMutationOptions<AuthRefreshResponse, AuthRefreshError, Options<AuthRefreshData>> => {
    const mutationOptions: UseMutationOptions<AuthRefreshResponse, AuthRefreshError, Options<AuthRefreshData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await AuthService.refresh({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const usersGetCurrentUserQueryKey = (options?: Options<UsersGetCurrentUserData>) => createQueryKey('usersGetCurrentUser', options);

/**
 * Get current user
 *
 * Get current user
 */
export const usersGetCurrentUserOptions = (options?: Options<UsersGetCurrentUserData>) => queryOptions<UsersGetCurrentUserResponse, UsersGetCurrentUserError, UsersGetCurrentUserResponse, ReturnType<typeof usersGetCurrentUserQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await UserService.getCurrentUser({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: usersGetCurrentUserQueryKey(options)
});

/**
 * Create Chat
 */
export const chatsCreateChatMutation = (options?: Partial<Options<ChatsCreateChatData>>): UseMutationOptions<ChatsCreateChatResponse, ChatsCreateChatError, Options<ChatsCreateChatData>> => {
    const mutationOptions: UseMutationOptions<ChatsCreateChatResponse, ChatsCreateChatError, Options<ChatsCreateChatData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await ChatService.createChat({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const serversGetMyServersQueryKey = (options?: Options<ServersGetMyServersData>) => createQueryKey('serversGetMyServers', options);

/**
 * Get My Servers
 */
export const serversGetMyServersOptions = (options?: Options<ServersGetMyServersData>) => queryOptions<ServersGetMyServersResponse, ServersGetMyServersError, ServersGetMyServersResponse, ReturnType<typeof serversGetMyServersQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ServerService.getMyServers({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: serversGetMyServersQueryKey(options)
});

/**
 * Create Server
 */
export const serversCreateServerMutation = (options?: Partial<Options<ServersCreateServerData>>): UseMutationOptions<ServersCreateServerResponse, ServersCreateServerError, Options<ServersCreateServerData>> => {
    const mutationOptions: UseMutationOptions<ServersCreateServerResponse, ServersCreateServerError, Options<ServersCreateServerData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await ServerService.createServer({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Update Server
 */
export const serversUpdateServerMutation = (options?: Partial<Options<ServersUpdateServerData>>): UseMutationOptions<ServersUpdateServerResponse, ServersUpdateServerError, Options<ServersUpdateServerData>> => {
    const mutationOptions: UseMutationOptions<ServersUpdateServerResponse, ServersUpdateServerError, Options<ServersUpdateServerData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await ServerService.updateServer({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete Server
 */
export const serversDeleteServerMutation = (options?: Partial<Options<ServersDeleteServerData>>): UseMutationOptions<ServersDeleteServerResponse, ServersDeleteServerError, Options<ServersDeleteServerData>> => {
    const mutationOptions: UseMutationOptions<ServersDeleteServerResponse, ServersDeleteServerError, Options<ServersDeleteServerData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await ServerService.deleteServer({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
