from typing import Protocol
from uuid import UUID

from src.modules.channels.domain.entities.channel import Channel
from src.modules.channels.domain.entities.dtos import ChannelCreate, ChannelUpdate


class ChannelRepository(Protocol):
    async def create(self, data: ChannelCreate) -> Channel: ...

    async def get_by_id(self, channel_id: UUID) -> Channel | None: ...

    async def find_by_name(self, server_id: UUID, name: str) -> Channel | None: ...

    async def update(self, channel_id: UUID, data: ChannelUpdate) -> Channel: ...

    async def delete(self, channel_id: UUID) -> None: ...

    async def count_by_server(self, server_id: UUID) -> int: ...

    async def increment_sequence(self, channel_id: UUID) -> int: ...
