// This file is auto-generated by @hey-api/openapi-ts

export const Body_Auth_loginSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: [
        'username',
        'password'
    ],
    title: 'Body_Auth-login'
} as const;

export const Body_Auth_logoutSchema = {
    properties: {
        refresh_token: {
            type: 'string',
            title: 'Refresh Token'
        }
    },
    type: 'object',
    required: [
        'refresh_token'
    ],
    title: 'Body_Auth-logout'
} as const;

export const Body_Auth_refreshSchema = {
    properties: {
        refresh_token: {
            type: 'string',
            title: 'Refresh Token'
        }
    },
    type: 'object',
    required: [
        'refresh_token'
    ],
    title: 'Body_Auth-refresh'
} as const;

export const ChannelMessageSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        sender_id: {
            type: 'string',
            format: 'uuid',
            title: 'Sender Id'
        },
        body: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Body'
        },
        sequence: {
            type: 'integer',
            title: 'Sequence'
        },
        parent_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Id'
        },
        is_edited: {
            type: 'boolean',
            title: 'Is Edited'
        },
        is_deleted: {
            type: 'boolean',
            title: 'Is Deleted'
        },
        deleted_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deleted At'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        channel_id: {
            type: 'string',
            format: 'uuid',
            title: 'Channel Id'
        }
    },
    type: 'object',
    required: [
        'id',
        'sender_id',
        'body',
        'sequence',
        'parent_id',
        'is_edited',
        'is_deleted',
        'deleted_at',
        'created_at',
        'updated_at',
        'channel_id'
    ],
    title: 'ChannelMessage'
} as const;

export const ChatCreateRequestSchema = {
    properties: {
        type: {
            $ref: '#/components/schemas/ChatType'
        },
        target_user_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Target User Id'
        },
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 300,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        member_ids: {
            anyOf: [
                {
                    items: {
                        type: 'string',
                        format: 'uuid'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Member Ids'
        }
    },
    type: 'object',
    required: [
        'type'
    ],
    title: 'ChatCreateRequest'
} as const;

export const ChatMessageSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        sender_id: {
            type: 'string',
            format: 'uuid',
            title: 'Sender Id'
        },
        body: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Body'
        },
        sequence: {
            type: 'integer',
            title: 'Sequence'
        },
        parent_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Id'
        },
        is_edited: {
            type: 'boolean',
            title: 'Is Edited'
        },
        is_deleted: {
            type: 'boolean',
            title: 'Is Deleted'
        },
        deleted_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deleted At'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        chat_id: {
            type: 'string',
            format: 'uuid',
            title: 'Chat Id'
        }
    },
    type: 'object',
    required: [
        'id',
        'sender_id',
        'body',
        'sequence',
        'parent_id',
        'is_edited',
        'is_deleted',
        'deleted_at',
        'created_at',
        'updated_at',
        'chat_id'
    ],
    title: 'ChatMessage'
} as const;

export const ChatSummaryPageSchema = {
    properties: {
        items: {
            items: {
                oneOf: [
                    {
                        $ref: '#/components/schemas/GroupChatSummary'
                    },
                    {
                        $ref: '#/components/schemas/PrivateChatSummary'
                    }
                ],
                discriminator: {
                    propertyName: 'type',
                    mapping: {
                        group: '#/components/schemas/GroupChatSummary',
                        private: '#/components/schemas/PrivateChatSummary'
                    }
                }
            },
            type: 'array',
            title: 'Items'
        },
        next_cursor: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Next Cursor'
        },
        total: {
            type: 'integer',
            title: 'Total'
        }
    },
    type: 'object',
    required: [
        'items',
        'next_cursor',
        'total'
    ],
    title: 'ChatSummaryPage'
} as const;

export const ChatTypeSchema = {
    type: 'string',
    enum: [
        'private',
        'group'
    ],
    title: 'ChatType'
} as const;

export const CreateServerInviteRequestSchema = {
    properties: {
        expires_in: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Expires In'
        },
        max_uses: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Max Uses'
        }
    },
    type: 'object',
    title: 'CreateServerInviteRequest'
} as const;

export const GroupChatSummarySchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        type: {
            type: 'string',
            const: 'group',
            title: 'Type'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        image_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url'
        },
        unread_count: {
            type: 'integer',
            title: 'Unread Count'
        },
        last_message: {
            anyOf: [
                {
                    $ref: '#/components/schemas/LastMessagePreview'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: [
        'id',
        'type',
        'name',
        'image_url',
        'unread_count',
        'last_message'
    ],
    title: 'GroupChatSummary'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                $ref: '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const LastMessagePreviewSchema = {
    properties: {
        sender_id: {
            type: 'string',
            format: 'uuid',
            title: 'Sender Id'
        },
        body: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Body'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: [
        'sender_id',
        'body',
        'created_at'
    ],
    title: 'LastMessagePreview'
} as const;

export const MessageCreateRequestSchema = {
    properties: {
        body: {
            type: 'string',
            maxLength: 2000,
            minLength: 1,
            title: 'Body'
        },
        parent_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Id'
        }
    },
    type: 'object',
    required: [
        'body'
    ],
    title: 'MessageCreateRequest'
} as const;

export const PrivateChatSummarySchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        type: {
            type: 'string',
            const: 'private',
            title: 'Type'
        },
        peer_id: {
            type: 'string',
            format: 'uuid',
            title: 'Peer Id'
        },
        peer_name: {
            type: 'string',
            title: 'Peer Name'
        },
        peer_avatar_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Peer Avatar Url'
        },
        unread_count: {
            type: 'integer',
            title: 'Unread Count'
        },
        last_message: {
            anyOf: [
                {
                    $ref: '#/components/schemas/LastMessagePreview'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: [
        'id',
        'type',
        'peer_id',
        'peer_name',
        'peer_avatar_url',
        'unread_count',
        'last_message'
    ],
    title: 'PrivateChatSummary'
} as const;

export const RegisterFormSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 64,
            minLength: 3,
            title: 'Name'
        },
        username: {
            type: 'string',
            maxLength: 32,
            minLength: 3,
            title: 'Username'
        },
        email: {
            type: 'string',
            maxLength: 32,
            minLength: 3,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 3,
            title: 'Password'
        }
    },
    type: 'object',
    required: [
        'name',
        'username',
        'email',
        'password'
    ],
    title: 'RegisterForm'
} as const;

export const ServerCreateRequestSchemaSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 300
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: [
        'name',
        'description'
    ],
    title: 'ServerCreateRequestSchema'
} as const;

export const ServerInviteSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        server_id: {
            type: 'string',
            format: 'uuid',
            title: 'Server Id'
        },
        code: {
            type: 'string',
            title: 'Code'
        },
        created_by: {
            type: 'string',
            format: 'uuid',
            title: 'Created By'
        },
        max_uses: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Max Uses'
        },
        use_count: {
            type: 'integer',
            title: 'Use Count'
        },
        expires_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Expires At'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: [
        'id',
        'server_id',
        'code',
        'created_by',
        'max_uses',
        'use_count',
        'expires_at',
        'created_at'
    ],
    title: 'ServerInvite'
} as const;

export const ServerInviteCodeSchema = {
    properties: {
        code: {
            type: 'string',
            title: 'Code'
        }
    },
    type: 'object',
    required: [
        'code'
    ],
    title: 'ServerInviteCode'
} as const;

export const ServerInviteWithStatusSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        server_id: {
            type: 'string',
            format: 'uuid',
            title: 'Server Id'
        },
        code: {
            type: 'string',
            title: 'Code'
        },
        created_by: {
            type: 'string',
            format: 'uuid',
            title: 'Created By'
        },
        max_uses: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Max Uses'
        },
        use_count: {
            type: 'integer',
            title: 'Use Count'
        },
        expires_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Expires At'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        validity_status: {
            type: 'string',
            enum: [
                'valid',
                'expired',
                'exhausted'
            ],
            title: 'Validity Status'
        }
    },
    type: 'object',
    required: [
        'id',
        'server_id',
        'code',
        'created_by',
        'max_uses',
        'use_count',
        'expires_at',
        'created_at',
        'validity_status'
    ],
    title: 'ServerInviteWithStatus'
} as const;

export const ServerMemberRoleSchema = {
    type: 'string',
    enum: [
        'owner',
        'member'
    ],
    title: 'ServerMemberRole'
} as const;

export const ServerMemberSchemaSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        server_id: {
            type: 'string',
            format: 'uuid',
            title: 'Server Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        role: {
            $ref: '#/components/schemas/ServerMemberRole'
        }
    },
    type: 'object',
    required: [
        'id',
        'server_id',
        'user_id',
        'role'
    ],
    title: 'ServerMemberSchema'
} as const;

export const ServerSchemaSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        icon_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Icon Url'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        member_count: {
            type: 'integer',
            title: 'Member Count'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: [
        'id',
        'name',
        'description',
        'icon_url',
        'owner_id',
        'member_count',
        'created_at',
        'updated_at'
    ],
    title: 'ServerSchema'
} as const;

export const ServerUpdateRequestSchemaSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 300,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ServerUpdateRequestSchema'
} as const;

export const ServerUserBriefSchemaSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        icon_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Icon Url'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        member_count: {
            type: 'integer',
            title: 'Member Count'
        },
        role: {
            $ref: '#/components/schemas/ServerMemberRole'
        },
        joined_at: {
            type: 'string',
            format: 'date-time',
            title: 'Joined At'
        }
    },
    type: 'object',
    required: [
        'id',
        'name',
        'icon_url',
        'owner_id',
        'member_count',
        'role',
        'joined_at'
    ],
    title: 'ServerUserBriefSchema'
} as const;

export const TokenPairSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        refresh_token: {
            type: 'string',
            title: 'Refresh Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: [
        'access_token',
        'refresh_token'
    ],
    title: 'TokenPair'
} as const;

export const UpdateOwnerIdSchemaSchema = {
    properties: {
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        }
    },
    type: 'object',
    required: [
        'owner_id'
    ],
    title: 'UpdateOwnerIdSchema'
} as const;

export const UserReadSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        email: {
            type: 'string',
            title: 'Email'
        },
        avatar_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avatar Url'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: [
        'id',
        'name',
        'username',
        'email',
        'avatar_url',
        'is_active',
        'created_at',
        'updated_at'
    ],
    title: 'UserRead'
} as const;

export const UserUpdateRequestSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 64
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        username: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 32,
                    minLength: 3
                },
                {
                    type: 'null'
                }
            ],
            title: 'Username'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 32,
                    minLength: 3,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateRequest'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: [
        'loc',
        'msg',
        'type'
    ],
    title: 'ValidationError'
} as const;
