// This file is auto-generated by @hey-api/openapi-ts

export const ChatCreateRequestSchemaSchema = {
    properties: {
        type: {
            $ref: '#/components/schemas/ChatType'
        },
        target_user_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Target User Id'
        },
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 300,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        member_ids: {
            anyOf: [
                {
                    items: {
                        type: 'string',
                        format: 'uuid'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Member Ids'
        }
    },
    type: 'object',
    required: [
        'type'
    ],
    title: 'ChatCreateRequestSchema'
} as const;

export const ChatTypeSchema = {
    type: 'string',
    enum: [
        'private',
        'group'
    ],
    title: 'ChatType'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                $ref: '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const RefreshTokenSchema = {
    properties: {
        refresh_token: {
            type: 'string',
            title: 'Refresh Token'
        }
    },
    type: 'object',
    required: [
        'refresh_token'
    ],
    title: 'RefreshToken'
} as const;

export const ServerCreateRequestSchemaSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 300
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: [
        'name'
    ],
    title: 'ServerCreateRequestSchema'
} as const;

export const ServerMemberRoleSchema = {
    type: 'string',
    enum: [
        'owner',
        'member'
    ],
    title: 'ServerMemberRole'
} as const;

export const ServerSchemaSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        icon_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Icon Url'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        member_count: {
            type: 'integer',
            title: 'Member Count'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: [
        'id',
        'name',
        'description',
        'icon_url',
        'owner_id',
        'member_count',
        'created_at',
        'updated_at'
    ],
    title: 'ServerSchema'
} as const;

export const ServerUpdateRequestSchemaSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 300
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ServerUpdateRequestSchema'
} as const;

export const TokenPairSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        refresh_token: {
            type: 'string',
            title: 'Refresh Token'
        }
    },
    type: 'object',
    required: [
        'access_token',
        'refresh_token'
    ],
    title: 'TokenPair'
} as const;

export const UserLoginSchemaSchema = {
    properties: {
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            title: 'Password'
        }
    },
    type: 'object',
    required: [
        'username',
        'password'
    ],
    title: 'UserLoginSchema',
    description: 'Schema for login a user'
} as const;

export const UserReadSchemaSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        email: {
            type: 'string',
            title: 'Email'
        },
        avatar_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avatar Url'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: [
        'id',
        'name',
        'username',
        'email',
        'avatar_url',
        'is_active',
        'created_at',
        'updated_at'
    ],
    title: 'UserReadSchema',
    description: 'Schema for get a user'
} as const;

export const UserRegisterSchemaSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        }
    },
    type: 'object',
    required: [
        'name',
        'username',
        'email',
        'password'
    ],
    title: 'UserRegisterSchema',
    description: 'Schema for creating a user'
} as const;

export const UserServerSummarySchemaSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        icon_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Icon Url'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        member_count: {
            type: 'integer',
            title: 'Member Count'
        },
        role: {
            $ref: '#/components/schemas/ServerMemberRole'
        },
        joined_at: {
            type: 'string',
            format: 'date-time',
            title: 'Joined At'
        }
    },
    type: 'object',
    required: [
        'id',
        'name',
        'icon_url',
        'owner_id',
        'member_count',
        'role',
        'joined_at'
    ],
    title: 'UserServerSummarySchema'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: [
        'loc',
        'msg',
        'type'
    ],
    title: 'ValidationError'
} as const;
