// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { AuthLoginUserData, AuthLoginUserErrors, AuthLoginUserResponses, AuthRefreshData, AuthRefreshErrors, AuthRefreshResponses, AuthRegisterUserData, AuthRegisterUserErrors, AuthRegisterUserResponses, ChatsCreateChatData, ChatsCreateChatErrors, ChatsCreateChatResponses, ServersCreateServerData, ServersCreateServerErrors, ServersCreateServerResponses, ServersDeleteServerData, ServersDeleteServerErrors, ServersDeleteServerResponses, ServersGetMyServersData, ServersGetMyServersErrors, ServersGetMyServersResponses, ServersUpdateServerData, ServersUpdateServerErrors, ServersUpdateServerResponses, UsersGetCurrentUserData, UsersGetCurrentUserErrors, UsersGetCurrentUserResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export class AuthService {
    /**
     * Register new user
     *
     * Register new user
     */
    public static registerUser<ThrowOnError extends boolean = false>(options: Options<AuthRegisterUserData, ThrowOnError>): RequestResult<AuthRegisterUserResponses, AuthRegisterUserErrors, ThrowOnError> {
        return (options.client ?? client).post<AuthRegisterUserResponses, AuthRegisterUserErrors, ThrowOnError>({
            url: '/api/v1/auth/register',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }

    /**
     * Login user
     *
     * Login user
     */
    public static loginUser<ThrowOnError extends boolean = false>(options: Options<AuthLoginUserData, ThrowOnError>): RequestResult<AuthLoginUserResponses, AuthLoginUserErrors, ThrowOnError> {
        return (options.client ?? client).post<AuthLoginUserResponses, AuthLoginUserErrors, ThrowOnError>({
            url: '/api/v1/auth/login',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }

    /**
     * Refresh token
     *
     * Refresh token
     */
    public static refresh<ThrowOnError extends boolean = false>(options?: Options<AuthRefreshData, ThrowOnError>): RequestResult<AuthRefreshResponses, AuthRefreshErrors, ThrowOnError> {
        return (options?.client ?? client).post<AuthRefreshResponses, AuthRefreshErrors, ThrowOnError>({
            url: '/api/v1/auth/refresh',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
}

export class UserService {
    /**
     * Get current user
     *
     * Get current user
     */
    public static getCurrentUser<ThrowOnError extends boolean = false>(options?: Options<UsersGetCurrentUserData, ThrowOnError>): RequestResult<UsersGetCurrentUserResponses, UsersGetCurrentUserErrors, ThrowOnError> {
        return (options?.client ?? client).get<UsersGetCurrentUserResponses, UsersGetCurrentUserErrors, ThrowOnError>({ url: '/api/v1/users/me', ...options });
    }
}

export class ChatService {
    /**
     * Create Chat
     */
    public static createChat<ThrowOnError extends boolean = false>(options: Options<ChatsCreateChatData, ThrowOnError>): RequestResult<ChatsCreateChatResponses, ChatsCreateChatErrors, ThrowOnError> {
        return (options.client ?? client).post<ChatsCreateChatResponses, ChatsCreateChatErrors, ThrowOnError>({
            url: '/api/v1/chats',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}

export class ServerService {
    /**
     * Get My Servers
     */
    public static getMyServers<ThrowOnError extends boolean = false>(options?: Options<ServersGetMyServersData, ThrowOnError>): RequestResult<ServersGetMyServersResponses, ServersGetMyServersErrors, ThrowOnError> {
        return (options?.client ?? client).get<ServersGetMyServersResponses, ServersGetMyServersErrors, ThrowOnError>({ url: '/api/v1/servers', ...options });
    }

    /**
     * Create Server
     */
    public static createServer<ThrowOnError extends boolean = false>(options: Options<ServersCreateServerData, ThrowOnError>): RequestResult<ServersCreateServerResponses, ServersCreateServerErrors, ThrowOnError> {
        return (options.client ?? client).post<ServersCreateServerResponses, ServersCreateServerErrors, ThrowOnError>({
            url: '/api/v1/servers',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }

    /**
     * Update Server
     */
    public static updateServer<ThrowOnError extends boolean = false>(options: Options<ServersUpdateServerData, ThrowOnError>): RequestResult<ServersUpdateServerResponses, ServersUpdateServerErrors, ThrowOnError> {
        return (options.client ?? client).patch<ServersUpdateServerResponses, ServersUpdateServerErrors, ThrowOnError>({
            url: '/api/v1/servers/update/{server_id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }

    /**
     * Delete Server
     */
    public static deleteServer<ThrowOnError extends boolean = false>(options: Options<ServersDeleteServerData, ThrowOnError>): RequestResult<ServersDeleteServerResponses, ServersDeleteServerErrors, ThrowOnError> {
        return (options.client ?? client).delete<ServersDeleteServerResponses, ServersDeleteServerErrors, ThrowOnError>({ url: '/api/v1/servers/delete/{server_id}', ...options });
    }
}
