// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type ClientMeta, type Options as Options2, type RequestResult, type TDataShape, urlSearchParamsBodySerializer } from './client';
import { client } from './client.gen';
import type { AuthLoginData, AuthLoginErrors, AuthLoginResponses, AuthLogoutData, AuthLogoutErrors, AuthLogoutResponses, AuthRefreshData, AuthRefreshErrors, AuthRefreshResponses, AuthRegisterData, AuthRegisterErrors, AuthRegisterResponses, ChannelsSendChannelMessageData, ChannelsSendChannelMessageErrors, ChannelsSendChannelMessageResponses, ChatsCreateChatData, ChatsCreateChatErrors, ChatsCreateChatResponses, ChatsGetMyChatsData, ChatsGetMyChatsErrors, ChatsGetMyChatsResponses, ChatsSendChatMessageData, ChatsSendChatMessageErrors, ChatsSendChatMessageResponses, ServersCreateInviteData, ServersCreateInviteErrors, ServersCreateInviteResponses, ServersCreateServerData, ServersCreateServerErrors, ServersCreateServerResponses, ServersDeleteInviteData, ServersDeleteInviteErrors, ServersDeleteInviteResponses, ServersDeleteServerData, ServersDeleteServerErrors, ServersDeleteServerResponses, ServersGetInvitesData, ServersGetInvitesErrors, ServersGetInvitesResponses, ServersGetMyServerData, ServersGetMyServerErrors, ServersGetMyServerResponses, ServersGetMyServersData, ServersGetMyServersResponses, ServersJoinServerData, ServersJoinServerErrors, ServersJoinServerResponses, ServersTransferOwnershipData, ServersTransferOwnershipErrors, ServersTransferOwnershipResponses, ServersUpdateServerData, ServersUpdateServerErrors, ServersUpdateServerResponses, UsersDeleteUserData, UsersDeleteUserResponses, UsersGetCurrentUserData, UsersGetCurrentUserResponses, UsersGetUserByIdData, UsersGetUserByIdErrors, UsersGetUserByIdResponses, UsersUpdateUserData, UsersUpdateUserErrors, UsersUpdateUserResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export class AuthService {
    /**
     * Register
     */
    public static register<ThrowOnError extends boolean = false>(options: Options<AuthRegisterData, ThrowOnError>): RequestResult<AuthRegisterResponses, AuthRegisterErrors, ThrowOnError> {
        return (options.client ?? client).post<AuthRegisterResponses, AuthRegisterErrors, ThrowOnError>({
            url: '/api/v1/auth/register',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Login
     */
    public static login<ThrowOnError extends boolean = false>(options: Options<AuthLoginData, ThrowOnError>): RequestResult<AuthLoginResponses, AuthLoginErrors, ThrowOnError> {
        return (options.client ?? client).post<AuthLoginResponses, AuthLoginErrors, ThrowOnError>({
            ...urlSearchParamsBodySerializer,
            url: '/api/v1/auth/login',
            ...options,
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded',
                ...options.headers
            }
        });
    }
    
    /**
     * Refresh token
     */
    public static refresh<ThrowOnError extends boolean = false>(options: Options<AuthRefreshData, ThrowOnError>): RequestResult<AuthRefreshResponses, AuthRefreshErrors, ThrowOnError> {
        return (options.client ?? client).post<AuthRefreshResponses, AuthRefreshErrors, ThrowOnError>({
            url: '/api/v1/auth/refresh',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Logout
     */
    public static logout<ThrowOnError extends boolean = false>(options: Options<AuthLogoutData, ThrowOnError>): RequestResult<AuthLogoutResponses, AuthLogoutErrors, ThrowOnError> {
        return (options.client ?? client).post<AuthLogoutResponses, AuthLogoutErrors, ThrowOnError>({
            url: '/api/v1/auth/logout',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}

export class UserService {
    /**
     * Delete User
     */
    public static deleteUser<ThrowOnError extends boolean = false>(options?: Options<UsersDeleteUserData, ThrowOnError>): RequestResult<UsersDeleteUserResponses, unknown, ThrowOnError> {
        return (options?.client ?? client).delete<UsersDeleteUserResponses, unknown, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/users/me',
            ...options
        });
    }
    
    /**
     * Get current user
     */
    public static getCurrentUser<ThrowOnError extends boolean = false>(options?: Options<UsersGetCurrentUserData, ThrowOnError>): RequestResult<UsersGetCurrentUserResponses, unknown, ThrowOnError> {
        return (options?.client ?? client).get<UsersGetCurrentUserResponses, unknown, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/users/me',
            ...options
        });
    }
    
    /**
     * Update current user
     */
    public static updateUser<ThrowOnError extends boolean = false>(options: Options<UsersUpdateUserData, ThrowOnError>): RequestResult<UsersUpdateUserResponses, UsersUpdateUserErrors, ThrowOnError> {
        return (options.client ?? client).patch<UsersUpdateUserResponses, UsersUpdateUserErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/users/me',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Get user by id
     */
    public static getUserById<ThrowOnError extends boolean = false>(options: Options<UsersGetUserByIdData, ThrowOnError>): RequestResult<UsersGetUserByIdResponses, UsersGetUserByIdErrors, ThrowOnError> {
        return (options.client ?? client).get<UsersGetUserByIdResponses, UsersGetUserByIdErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/users/{user_id}',
            ...options
        });
    }
}

export class ChatService {
    /**
     * Send Chat Message
     */
    public static sendChatMessage<ThrowOnError extends boolean = false>(options: Options<ChatsSendChatMessageData, ThrowOnError>): RequestResult<ChatsSendChatMessageResponses, ChatsSendChatMessageErrors, ThrowOnError> {
        return (options.client ?? client).post<ChatsSendChatMessageResponses, ChatsSendChatMessageErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/chats/{chat_id}/messages',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Get My Chats
     */
    public static getMyChats<ThrowOnError extends boolean = false>(options?: Options<ChatsGetMyChatsData, ThrowOnError>): RequestResult<ChatsGetMyChatsResponses, ChatsGetMyChatsErrors, ThrowOnError> {
        return (options?.client ?? client).get<ChatsGetMyChatsResponses, ChatsGetMyChatsErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/chats',
            ...options
        });
    }
    
    /**
     * Create Chat
     */
    public static createChat<ThrowOnError extends boolean = false>(options: Options<ChatsCreateChatData, ThrowOnError>): RequestResult<ChatsCreateChatResponses, ChatsCreateChatErrors, ThrowOnError> {
        return (options.client ?? client).post<ChatsCreateChatResponses, ChatsCreateChatErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/chats',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}

export class ChatMessageService {
    /**
     * Send Chat Message
     */
    public static sendChatMessage<ThrowOnError extends boolean = false>(options: Options<ChatsSendChatMessageData, ThrowOnError>): RequestResult<ChatsSendChatMessageResponses, ChatsSendChatMessageErrors, ThrowOnError> {
        return (options.client ?? client).post<ChatsSendChatMessageResponses, ChatsSendChatMessageErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/chats/{chat_id}/messages',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}

export class ServerService {
    /**
     * Get Invites
     */
    public static getInvites<ThrowOnError extends boolean = false>(options: Options<ServersGetInvitesData, ThrowOnError>): RequestResult<ServersGetInvitesResponses, ServersGetInvitesErrors, ThrowOnError> {
        return (options.client ?? client).get<ServersGetInvitesResponses, ServersGetInvitesErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/servers/{server_id}/invites',
            ...options
        });
    }
    
    /**
     * Create Invite
     */
    public static createInvite<ThrowOnError extends boolean = false>(options: Options<ServersCreateInviteData, ThrowOnError>): RequestResult<ServersCreateInviteResponses, ServersCreateInviteErrors, ThrowOnError> {
        return (options.client ?? client).post<ServersCreateInviteResponses, ServersCreateInviteErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/servers/{server_id}/invites',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Delete Invite
     */
    public static deleteInvite<ThrowOnError extends boolean = false>(options: Options<ServersDeleteInviteData, ThrowOnError>): RequestResult<ServersDeleteInviteResponses, ServersDeleteInviteErrors, ThrowOnError> {
        return (options.client ?? client).delete<ServersDeleteInviteResponses, ServersDeleteInviteErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/servers/{server_id}/invites/{code}',
            ...options
        });
    }
    
    /**
     * Get My Servers
     */
    public static getMyServers<ThrowOnError extends boolean = false>(options?: Options<ServersGetMyServersData, ThrowOnError>): RequestResult<ServersGetMyServersResponses, unknown, ThrowOnError> {
        return (options?.client ?? client).get<ServersGetMyServersResponses, unknown, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/servers',
            ...options
        });
    }
    
    /**
     * Create Server
     */
    public static createServer<ThrowOnError extends boolean = false>(options: Options<ServersCreateServerData, ThrowOnError>): RequestResult<ServersCreateServerResponses, ServersCreateServerErrors, ThrowOnError> {
        return (options.client ?? client).post<ServersCreateServerResponses, ServersCreateServerErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/servers',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Join Server
     */
    public static joinServer<ThrowOnError extends boolean = false>(options: Options<ServersJoinServerData, ThrowOnError>): RequestResult<ServersJoinServerResponses, ServersJoinServerErrors, ThrowOnError> {
        return (options.client ?? client).post<ServersJoinServerResponses, ServersJoinServerErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/servers/join',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Transfer Ownership
     */
    public static transferOwnership<ThrowOnError extends boolean = false>(options: Options<ServersTransferOwnershipData, ThrowOnError>): RequestResult<ServersTransferOwnershipResponses, ServersTransferOwnershipErrors, ThrowOnError> {
        return (options.client ?? client).post<ServersTransferOwnershipResponses, ServersTransferOwnershipErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/servers/{server_id}/transfer',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Delete Server
     */
    public static deleteServer<ThrowOnError extends boolean = false>(options: Options<ServersDeleteServerData, ThrowOnError>): RequestResult<ServersDeleteServerResponses, ServersDeleteServerErrors, ThrowOnError> {
        return (options.client ?? client).delete<ServersDeleteServerResponses, ServersDeleteServerErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/servers/{server_id}',
            ...options
        });
    }
    
    /**
     * Get My Server
     */
    public static getMyServer<ThrowOnError extends boolean = false>(options: Options<ServersGetMyServerData, ThrowOnError>): RequestResult<ServersGetMyServerResponses, ServersGetMyServerErrors, ThrowOnError> {
        return (options.client ?? client).get<ServersGetMyServerResponses, ServersGetMyServerErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/servers/{server_id}',
            ...options
        });
    }
    
    /**
     * Update Server
     */
    public static updateServer<ThrowOnError extends boolean = false>(options: Options<ServersUpdateServerData, ThrowOnError>): RequestResult<ServersUpdateServerResponses, ServersUpdateServerErrors, ThrowOnError> {
        return (options.client ?? client).patch<ServersUpdateServerResponses, ServersUpdateServerErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/servers/{server_id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}

export class ServerInviteService {
    /**
     * Get Invites
     */
    public static getInvites<ThrowOnError extends boolean = false>(options: Options<ServersGetInvitesData, ThrowOnError>): RequestResult<ServersGetInvitesResponses, ServersGetInvitesErrors, ThrowOnError> {
        return (options.client ?? client).get<ServersGetInvitesResponses, ServersGetInvitesErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/servers/{server_id}/invites',
            ...options
        });
    }
    
    /**
     * Create Invite
     */
    public static createInvite<ThrowOnError extends boolean = false>(options: Options<ServersCreateInviteData, ThrowOnError>): RequestResult<ServersCreateInviteResponses, ServersCreateInviteErrors, ThrowOnError> {
        return (options.client ?? client).post<ServersCreateInviteResponses, ServersCreateInviteErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/servers/{server_id}/invites',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Delete Invite
     */
    public static deleteInvite<ThrowOnError extends boolean = false>(options: Options<ServersDeleteInviteData, ThrowOnError>): RequestResult<ServersDeleteInviteResponses, ServersDeleteInviteErrors, ThrowOnError> {
        return (options.client ?? client).delete<ServersDeleteInviteResponses, ServersDeleteInviteErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/servers/{server_id}/invites/{code}',
            ...options
        });
    }
}

export class ChannelService {
    /**
     * Send Channel Message
     */
    public static sendChannelMessage<ThrowOnError extends boolean = false>(options: Options<ChannelsSendChannelMessageData, ThrowOnError>): RequestResult<ChannelsSendChannelMessageResponses, ChannelsSendChannelMessageErrors, ThrowOnError> {
        return (options.client ?? client).post<ChannelsSendChannelMessageResponses, ChannelsSendChannelMessageErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/channels/{channel_id}/messages',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}

export class ChannelMessageService {
    /**
     * Send Channel Message
     */
    public static sendChannelMessage<ThrowOnError extends boolean = false>(options: Options<ChannelsSendChannelMessageData, ThrowOnError>): RequestResult<ChannelsSendChannelMessageResponses, ChannelsSendChannelMessageErrors, ThrowOnError> {
        return (options.client ?? client).post<ChannelsSendChannelMessageResponses, ChannelsSendChannelMessageErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/channels/{channel_id}/messages',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}
