// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Body_Auth-refresh
 */
export type BodyAuthRefresh = {
    /**
     * Refresh Token
     */
    refresh_token?: string;
};

/**
 * ChatCreateRequestSchema
 */
export type ChatCreateRequestSchema = {
    type: ChatType;
    /**
     * Target User Id
     */
    target_user_id?: string | null;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Member Ids
     */
    member_ids?: Array<string> | null;
};

/**
 * ChatType
 */
export const ChatType = { PRIVATE: 'private', GROUP: 'group' } as const;

/**
 * ChatType
 */
export type ChatType = typeof ChatType[keyof typeof ChatType];

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ServerCreateRequestSchema
 */
export type ServerCreateRequestSchema = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ServerSchema
 */
export type ServerSchema = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Icon Url
     */
    icon_url: string | null;
    /**
     * Owner Id
     */
    owner_id: string;
    /**
     * Member Count
     */
    member_count: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ServerUpdateRequestSchema
 */
export type ServerUpdateRequestSchema = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * TokenPair
 */
export type TokenPair = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Refresh Token
     */
    refresh_token: string;
};

/**
 * UserLoginSchema
 *
 * Schema for login a user
 */
export type UserLoginSchema = {
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
};

/**
 * UserReadSchema
 *
 * Schema for get a user
 */
export type UserReadSchema = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Username
     */
    username: string;
    /**
     * Email
     */
    email: string;
    /**
     * Avatar Url
     */
    avatar_url: string | null;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * UserRegisterSchema
 *
 * Schema for creating a user
 */
export type UserRegisterSchema = {
    /**
     * Name
     */
    name: string;
    /**
     * Username
     */
    username: string;
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type AuthRegisterUserData = {
    body: UserRegisterSchema;
    path?: never;
    query?: never;
    url: '/api/v1/auth/register';
};

export type AuthRegisterUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthRegisterUserError = AuthRegisterUserErrors[keyof AuthRegisterUserErrors];

export type AuthRegisterUserResponses = {
    /**
     * Successful Response
     */
    201: UserReadSchema;
};

export type AuthRegisterUserResponse = AuthRegisterUserResponses[keyof AuthRegisterUserResponses];

export type AuthLoginUserData = {
    body: UserLoginSchema;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type AuthLoginUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthLoginUserError = AuthLoginUserErrors[keyof AuthLoginUserErrors];

export type AuthLoginUserResponses = {
    /**
     * Successful Response
     */
    200: TokenPair;
};

export type AuthLoginUserResponse = AuthLoginUserResponses[keyof AuthLoginUserResponses];

export type AuthRefreshData = {
    body?: BodyAuthRefresh;
    path?: never;
    query?: never;
    url: '/api/v1/auth/refresh';
};

export type AuthRefreshErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthRefreshError = AuthRefreshErrors[keyof AuthRefreshErrors];

export type AuthRefreshResponses = {
    /**
     * Successful Response
     */
    200: TokenPair;
};

export type AuthRefreshResponse = AuthRefreshResponses[keyof AuthRefreshResponses];

export type UsersGetCurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersGetCurrentUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersGetCurrentUserError = UsersGetCurrentUserErrors[keyof UsersGetCurrentUserErrors];

export type UsersGetCurrentUserResponses = {
    /**
     * Successful Response
     */
    200: UserReadSchema;
};

export type UsersGetCurrentUserResponse = UsersGetCurrentUserResponses[keyof UsersGetCurrentUserResponses];

export type ChatsCreateChatData = {
    body: ChatCreateRequestSchema;
    path?: never;
    query?: never;
    url: '/api/v1/chats';
};

export type ChatsCreateChatErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChatsCreateChatError = ChatsCreateChatErrors[keyof ChatsCreateChatErrors];

export type ChatsCreateChatResponses = {
    /**
     * Successful Response
     */
    201: ChatCreateRequestSchema;
};

export type ChatsCreateChatResponse = ChatsCreateChatResponses[keyof ChatsCreateChatResponses];

export type ServersCreateServerData = {
    body: ServerCreateRequestSchema;
    path?: never;
    query?: never;
    url: '/api/v1/servers';
};

export type ServersCreateServerErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ServersCreateServerError = ServersCreateServerErrors[keyof ServersCreateServerErrors];

export type ServersCreateServerResponses = {
    /**
     * Successful Response
     */
    201: ServerSchema;
};

export type ServersCreateServerResponse = ServersCreateServerResponses[keyof ServersCreateServerResponses];

export type ServersUpdateServerData = {
    body: ServerUpdateRequestSchema;
    path: {
        /**
         * Server Id
         */
        server_id: string;
    };
    query?: never;
    url: '/api/v1/servers/update/{server_id}';
};

export type ServersUpdateServerErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ServersUpdateServerError = ServersUpdateServerErrors[keyof ServersUpdateServerErrors];

export type ServersUpdateServerResponses = {
    /**
     * Successful Response
     */
    200: ServerSchema;
};

export type ServersUpdateServerResponse = ServersUpdateServerResponses[keyof ServersUpdateServerResponses];

export type ServersDeleteServerData = {
    body?: never;
    path: {
        /**
         * Server Id
         */
        server_id: string;
    };
    query?: never;
    url: '/api/v1/servers/delete/{server_id}';
};

export type ServersDeleteServerErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ServersDeleteServerError = ServersDeleteServerErrors[keyof ServersDeleteServerErrors];

export type ServersDeleteServerResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type ServersDeleteServerResponse = ServersDeleteServerResponses[keyof ServersDeleteServerResponses];
