// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Body_Auth-login
 */
export type BodyAuthLogin = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * Body_Auth-logout
 */
export type BodyAuthLogout = {
    /**
     * Refresh Token
     */
    refresh_token: string;
};

/**
 * Body_Auth-refresh
 */
export type BodyAuthRefresh = {
    /**
     * Refresh Token
     */
    refresh_token: string;
};

/**
 * ChatCreateRequest
 */
export type ChatCreateRequest = {
    type: ChatType;
    /**
     * Target User Id
     */
    target_user_id?: string | null;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Member Ids
     */
    member_ids?: Array<string> | null;
};

/**
 * ChatSummaryPage
 */
export type ChatSummaryPage = {
    /**
     * Items
     */
    items: Array<({
        type: 'group';
    } & GroupChatSummary) | ({
        type: 'private';
    } & PrivateChatSummary)>;
    /**
     * Next Cursor
     */
    next_cursor: string | null;
    /**
     * Total
     */
    total: number;
};

/**
 * ChatType
 */
export const ChatType = { PRIVATE: 'private', GROUP: 'group' } as const;

/**
 * ChatType
 */
export type ChatType = typeof ChatType[keyof typeof ChatType];

/**
 * GroupChatSummary
 */
export type GroupChatSummary = {
    /**
     * Id
     */
    id: string;
    /**
     * Type
     */
    type: 'group';
    /**
     * Name
     */
    name: string;
    /**
     * Image Url
     */
    image_url: string | null;
    /**
     * Unread Count
     */
    unread_count: number;
    last_message: LastMessagePreview | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LastMessagePreview
 */
export type LastMessagePreview = {
    /**
     * Sender Id
     */
    sender_id: string;
    /**
     * Body
     */
    body: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * PrivateChatSummary
 */
export type PrivateChatSummary = {
    /**
     * Id
     */
    id: string;
    /**
     * Type
     */
    type: 'private';
    /**
     * Peer Id
     */
    peer_id: string;
    /**
     * Peer Name
     */
    peer_name: string;
    /**
     * Peer Avatar Url
     */
    peer_avatar_url: string | null;
    /**
     * Unread Count
     */
    unread_count: number;
    last_message: LastMessagePreview | null;
};

/**
 * RegisterForm
 */
export type RegisterForm = {
    /**
     * Name
     */
    name: string;
    /**
     * Username
     */
    username: string;
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * ServerCreateRequestSchema
 */
export type ServerCreateRequestSchema = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ServerMemberRole
 */
export const ServerMemberRole = { OWNER: 'owner', MEMBER: 'member' } as const;

/**
 * ServerMemberRole
 */
export type ServerMemberRole = typeof ServerMemberRole[keyof typeof ServerMemberRole];

/**
 * ServerSchema
 */
export type ServerSchema = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Icon Url
     */
    icon_url: string | null;
    /**
     * Owner Id
     */
    owner_id: string;
    /**
     * Member Count
     */
    member_count: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ServerUpdateRequestSchema
 */
export type ServerUpdateRequestSchema = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ServerUserBriefSchema
 */
export type ServerUserBriefSchema = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Icon Url
     */
    icon_url: string | null;
    /**
     * Owner Id
     */
    owner_id: string;
    /**
     * Member Count
     */
    member_count: number;
    role: ServerMemberRole;
    /**
     * Joined At
     */
    joined_at: string;
};

/**
 * TokenPair
 */
export type TokenPair = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Refresh Token
     */
    refresh_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UserRead
 */
export type UserRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Username
     */
    username: string;
    /**
     * Email
     */
    email: string;
    /**
     * Avatar Url
     */
    avatar_url: string | null;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * UserUpdateRequest
 */
export type UserUpdateRequest = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Username
     */
    username?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type AuthRegisterData = {
    body: RegisterForm;
    path?: never;
    query?: never;
    url: '/api/v1/auth/register';
};

export type AuthRegisterErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthRegisterError = AuthRegisterErrors[keyof AuthRegisterErrors];

export type AuthRegisterResponses = {
    /**
     * Successful Response
     */
    201: UserRead;
};

export type AuthRegisterResponse = AuthRegisterResponses[keyof AuthRegisterResponses];

export type AuthLoginData = {
    body: BodyAuthLogin;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type AuthLoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthLoginError = AuthLoginErrors[keyof AuthLoginErrors];

export type AuthLoginResponses = {
    /**
     * Successful Response
     */
    200: TokenPair;
};

export type AuthLoginResponse = AuthLoginResponses[keyof AuthLoginResponses];

export type AuthRefreshData = {
    body: BodyAuthRefresh;
    path?: never;
    query?: never;
    url: '/api/v1/auth/refresh';
};

export type AuthRefreshErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthRefreshError = AuthRefreshErrors[keyof AuthRefreshErrors];

export type AuthRefreshResponses = {
    /**
     * Successful Response
     */
    200: TokenPair;
};

export type AuthRefreshResponse = AuthRefreshResponses[keyof AuthRefreshResponses];

export type AuthLogoutData = {
    body: BodyAuthLogout;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type AuthLogoutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthLogoutError = AuthLogoutErrors[keyof AuthLogoutErrors];

export type AuthLogoutResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type AuthLogoutResponse = AuthLogoutResponses[keyof AuthLogoutResponses];

export type UsersDeleteUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersDeleteUserResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type UsersDeleteUserResponse = UsersDeleteUserResponses[keyof UsersDeleteUserResponses];

export type UsersGetCurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersGetCurrentUserResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type UsersGetCurrentUserResponse = UsersGetCurrentUserResponses[keyof UsersGetCurrentUserResponses];

export type UsersUpdateUserData = {
    body: UserUpdateRequest;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdateUserError = UsersUpdateUserErrors[keyof UsersUpdateUserErrors];

export type UsersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type UsersUpdateUserResponse = UsersUpdateUserResponses[keyof UsersUpdateUserResponses];

export type UsersGetUserByIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersGetUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersGetUserByIdError = UsersGetUserByIdErrors[keyof UsersGetUserByIdErrors];

export type UsersGetUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type UsersGetUserByIdResponse = UsersGetUserByIdResponses[keyof UsersGetUserByIdResponses];

export type ChatsGetMyChatsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Cursor
         */
        cursor?: string | null;
    };
    url: '/api/v1/chats';
};

export type ChatsGetMyChatsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChatsGetMyChatsError = ChatsGetMyChatsErrors[keyof ChatsGetMyChatsErrors];

export type ChatsGetMyChatsResponses = {
    /**
     * Successful Response
     */
    200: ChatSummaryPage;
};

export type ChatsGetMyChatsResponse = ChatsGetMyChatsResponses[keyof ChatsGetMyChatsResponses];

export type ChatsCreateChatData = {
    body: ChatCreateRequest;
    path?: never;
    query?: never;
    url: '/api/v1/chats';
};

export type ChatsCreateChatErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChatsCreateChatError = ChatsCreateChatErrors[keyof ChatsCreateChatErrors];

export type ChatsCreateChatResponses = {
    /**
     * Successful Response
     */
    201: ChatCreateRequest;
};

export type ChatsCreateChatResponse = ChatsCreateChatResponses[keyof ChatsCreateChatResponses];

export type ServersGetMyServersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/servers';
};

export type ServersGetMyServersResponses = {
    /**
     * Response Servers-Get My Servers
     *
     * Successful Response
     */
    200: Array<ServerUserBriefSchema>;
};

export type ServersGetMyServersResponse = ServersGetMyServersResponses[keyof ServersGetMyServersResponses];

export type ServersCreateServerData = {
    body: ServerCreateRequestSchema;
    path?: never;
    query?: never;
    url: '/api/v1/servers';
};

export type ServersCreateServerErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ServersCreateServerError = ServersCreateServerErrors[keyof ServersCreateServerErrors];

export type ServersCreateServerResponses = {
    /**
     * Successful Response
     */
    201: ServerSchema;
};

export type ServersCreateServerResponse = ServersCreateServerResponses[keyof ServersCreateServerResponses];

export type ServersDeleteServerData = {
    body?: never;
    path: {
        /**
         * Server Id
         */
        server_id: string;
    };
    query?: never;
    url: '/api/v1/servers/{server_id}';
};

export type ServersDeleteServerErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ServersDeleteServerError = ServersDeleteServerErrors[keyof ServersDeleteServerErrors];

export type ServersDeleteServerResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type ServersDeleteServerResponse = ServersDeleteServerResponses[keyof ServersDeleteServerResponses];

export type ServersGetMyServerData = {
    body?: never;
    path: {
        /**
         * Server Id
         */
        server_id: string;
    };
    query?: never;
    url: '/api/v1/servers/{server_id}';
};

export type ServersGetMyServerErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ServersGetMyServerError = ServersGetMyServerErrors[keyof ServersGetMyServerErrors];

export type ServersGetMyServerResponses = {
    /**
     * Successful Response
     */
    200: ServerSchema;
};

export type ServersGetMyServerResponse = ServersGetMyServerResponses[keyof ServersGetMyServerResponses];

export type ServersUpdateServerData = {
    body: ServerUpdateRequestSchema;
    path: {
        /**
         * Server Id
         */
        server_id: string;
    };
    query?: never;
    url: '/api/v1/servers/{server_id}';
};

export type ServersUpdateServerErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ServersUpdateServerError = ServersUpdateServerErrors[keyof ServersUpdateServerErrors];

export type ServersUpdateServerResponses = {
    /**
     * Successful Response
     */
    200: ServerSchema;
};

export type ServersUpdateServerResponse = ServersUpdateServerResponses[keyof ServersUpdateServerResponses];
