/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as HomeDmsChatIdRouteImport } from './routes/home/dms.$chatId'
import { Route as HomeServersServerIdRouteImport } from './routes/home/servers.$serverId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRoute,
} as any)
const HomeDmsChatIdRoute = HomeDmsChatIdRouteImport.update({
  id: '/dms/$chatId',
  path: '/dms/$chatId',
  getParentRoute: () => HomeRoute,
} as any)
const HomeServersServerIdRoute = HomeServersServerIdRouteImport.update({
  id: '/servers/$serverId',
  path: '/servers/$serverId',
  getParentRoute: () => HomeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/home/': typeof HomeIndexRoute
  '/home/dms/$chatId': typeof HomeDmsChatIdRoute
  '/home/servers/$serverId': typeof HomeServersServerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/home': typeof HomeIndexRoute
  '/home/dms/$chatId': typeof HomeDmsChatIdRoute
  '/home/servers/$serverId': typeof HomeServersServerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/home/': typeof HomeIndexRoute
  '/home/dms/$chatId': typeof HomeDmsChatIdRoute
  '/home/servers/$serverId': typeof HomeServersServerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/login'
    | '/register'
    | '/home/'
    | '/home/dms/$chatId'
    | '/home/servers/$serverId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/home'
    | '/home/dms/$chatId'
    | '/home/servers/$serverId'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/login'
    | '/register'
    | '/home/'
    | '/home/dms/$chatId'
    | '/home/servers/$serverId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRoute
    }
    '/home/dms/$chatId': {
      id: '/home/dms/$chatId'
      path: '/dms/$chatId'
      fullPath: '/home/dms/$chatId'
      preLoaderRoute: typeof HomeDmsChatIdRouteImport
      parentRoute: typeof HomeRoute
    }
    '/home/servers/$serverId': {
      id: '/home/servers/$serverId'
      path: '/servers/$serverId'
      fullPath: '/home/servers/$serverId'
      preLoaderRoute: typeof HomeServersServerIdRouteImport
      parentRoute: typeof HomeRoute
    }
  }
}

interface HomeRouteChildren {
  HomeIndexRoute: typeof HomeIndexRoute
  HomeDmsChatIdRoute: typeof HomeDmsChatIdRoute
  HomeServersServerIdRoute: typeof HomeServersServerIdRoute
}

const HomeRouteChildren: HomeRouteChildren = {
  HomeIndexRoute: HomeIndexRoute,
  HomeDmsChatIdRoute: HomeDmsChatIdRoute,
  HomeServersServerIdRoute: HomeServersServerIdRoute,
}

const HomeRouteWithChildren = HomeRoute._addFileChildren(HomeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
